<?php
// Environment Configuration for Merlo Stone Website
// Generated by deployment script on 3/24/2025, 9:43:29 PM

// reCAPTCHA Configuration  
define('RECAPTCHA_SECRET_KEY', '6Le62v4qAAAAAAvJOTQjJsi3cOCwxpZZAz3rUTom');

// Email Configuration
define('EMAIL_TO', 'davemerlo@comcast.net');
define('EMAIL_BCC', 'bdmerlo@gmail.com');

// Debug/Logging Settings
define('ENABLE_DEBUG_LOGGING', false);
?>